 name: Deploy to S3

     on:
       push:
         branches:
           - main  # Запускать при пуше в основную ветку (можно изменить)

     jobs:
       deploy:
#           runs-on: ubuntu-latest
          workflow_dispatch:  # Добавляем ручной запуск
         steps:
           - name: Checkout repository
             uses: actions/checkout@v2

          
           - name: Deploy to S3
             env:
               AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
               AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               AWS_REGION: ${{ secrets.AWS_REGION }}
               AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
             run: |
               aws s3 sync . s3://$AWS_S3_BUCKET --exclude ".git/*" --exclude ".github/*" --exclude ".gitattributes" --delete
     
